on: 
  push: 
    branches:
      - master
name: Publish Website
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - uses: actions/setup-node@master
      - run: npm ci
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./dist
